# Generated by Django 5.1 on 2024-09-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(),
        ),
    ]
