# Generated by Django 5.1 on 2024-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
